### ISSUE TITLE
Can this engine solve the floating point difference between Android and ios?

### ISSUE THREAD

**Issue by Vi-jay** [shakiba/planck.js#174]
Can this engine solve the floating point difference between Android and ios?

**Comment by zOadT** [comment]
Unfortunately no. Planck just uses the floating point arithmetic of the JS engine it runs. As far as I know JS engines don't do any kind of floating point "normalization"

**Comment by Vi-jay** [comment]
Okay thank you

**Comment by Vi-jay** [comment]
> Unfortunately no. Planck just uses the floating point arithmetic of the JS engine it runs. As far as I know JS engines don't do any kind of floating point "normalization"
Hi senior, how do you synchronize the physics engine on different devices? I tried many ways to no avail

**Comment by zOadT** [comment]
I don't have experience in syncing physics worlds by myself, but I think the typical approach is to send the whole world state after some interval to get everyone back on the same state. But probably you already tried that... (Maybe it helps you to know that there is a method to serialize and deserialize objects in Planck.js)

Your problem is pretty difficult and depends on what exactly you want to accomplish

**Comment by Vi-jay** [comment]
> I don't have experience in syncing physics worlds by myself, but I think the typical approach is to send the whole world state after some interval to get everyone back on the same state. But probably you already tried that... (Maybe it helps you to know that there is a method to serialize and deserialize objects in Planck.js)
> 
> Your problem is pretty difficult and depends on what exactly you want to accomplish

Thank you for your help, I found a solution, your reply is very helpful to me
