### ISSUE TITLE
Full restitution bodies moving at a slow diagonal vector do not bounce

### ISSUE THREAD

**Issue by quinton-ashley** [shakiba/planck.js#217]
I found this example of Pong in planck.js.

https://codepen.io/bhavyam-goyal/pen/JVgwrK?editors=0010

Is there a way to implement Pong in planck.js, with zero gravity full restitution bouncing, without customizing the collision? When I try using 0 gravity, 0 friction, and a restitution of 1 for all bodies the results are not good, the ball slows down really quickly when colliding against other dynamic or static shape bodies.

Yet in this example, the ball keeps going at the same speed forever as expected.

https://molleindustria.github.io/p5.play/examples/v3.html?fileName=tunneling.js

Is there a way to get circles to bounce off polygons and retain full speed? Do I have to change mass or density or something else too? I also noticed in this example sometimes the circles get stuck on walls. I think these two problems are related somehow.

https://molleindustria.github.io/p5.play/examples/v3.html?fileName=ballPit.js

Note that all the bounce function does in these examples is set the friction to 0 and restitution to 1 of the bodies. What am I missing here, how do I get a full bounce? Thanks for reading, I hope to get a response soon. I am computer science teacher and I'm trying to use planck.js behind the scenes in a new version of p5.play (v3) to make it easier for beginners to make 2D games.

You can take a look at some more of my p5.play v3 examples here if you're curious:
https://github.com/molleindustria/p5.play/wiki/New-Features-in-p5.play-Version-3

**Comment by zOadT** [comment]
Hey! Unfortunately, I think the problem boils down to the fact that box2d isn't designed to produce exact results (see [the box2d FAQ](https://box2d.org/documentation/md__d_1__git_hub_box2d_docs__f_a_q.html#autotoc_md150). And so energy can be lost in collisions (see https://www.iforce2d.net/b2dtut/fixtures#restitution).

The tunneling example probably can resolve most collisions by multiplying with -1 because the walls are perfectly horizontal (resp. vertical) so there are no floating point errors involved.

I don't really know an elegant solution to this problem. If you don't want your students to deal with collision callbacks: You could provide them a function that recieves a list of bodies and the desired total impulse and scales the velocity of the bodies accordingly.

Hopefully these informations are a bit helpful to you. The p5.play project looks cool!

**Comment by quinton-ashley** [comment]
Thanks! I did a bit more testing and now I've properly identified the problem. It wasn't related to the kind of shape, it's just when the ball is moving in a slow diagonal. Here's a bare-bones example showcasing the problem:

https://molleindustria.github.io/p5.play/examples/v3.html?fileName=bug0.js

Your idea for scaling the velocities is a smart workaround but I'd like to get to the root cause of the bug!

**Comment by quinton-ashley** [comment]
Which section of planck does the bounce calculation of the new velocities for each body in a contact? I'm trying to search for it in the debugger but I can't seem to find it.

**Comment by quinton-ashley** [comment]
Found it on line 5626

**Comment by quinton-ashley** [comment]
I found the solution! Turns out there is a velocity threshold in settings: `planck.Settings.velocityThreshold` by default it is set to 1 so any bounce slower than that will not be calculated. I assume this is for performance reasons, which makes sense I guess, but a default threshold of 1 is way to high in my opinion. I would suggest changing the default to .49 at least.
