### ISSUE TITLE
Pickup (remove) items on overlap without collision impact resolution

### ISSUE THREAD

**Issue by quinton-ashley** [shakiba/planck.js#219]
I'm trying to setup a simple system for overlap and collision detection in p5.play v3 before starting I read through the relevant wiki page on Contacts https://github.com/shakiba/planck.js/wiki/Contact

Check out this example of what I'm trying to do:
- picking up an item should not cause the player sprite to be moved or rotated in any way
- picking up an item should happen only when the item and player sprite actually make contact and overlap

https://molleindustria.github.io/p5.play/examples/v3.html?fileName=pickup.js

Behind the scenes I'm using shouldCollide to prevent collisions between the player sprite and any sprite from the items group. I also save the callback and run it after the time step.

```js
pl.Fixture.prototype.shouldCollide = function (that) {
    // should this and that collide?
    const a = this.m_body.sprite;
    const b = that.m_body.sprite;
    
    let cb = _findContactCB('overlaps', a, b);
    if (cb) {
	    if (typeof cb == 'function') {
		    contacts.push([cb, a, b]);
	    }
	    return false;
    }
    cb = _findContactCB('overlaps', b, a);
    if (cb) {
	    if (typeof cb == 'function') {
		    contacts.push([cb, b, a]);
	    }
	    return false;
    }
    
    return true;
 };
```

```js
// in the updateSprites function

world.step(timeStep || 1 / 60, velocityIterations || 8, positionIterations || 3);

for (let c of contacts) {
	c[0](c[1], c[2]);
}
contacts = [];
```

https://github.com/molleindustria/p5.play/blob/gh-pages/v3/p5.play.js

I know that the problem here is that shouldCollide is called in anticipation of possible contact between objects. Therefore sometimes the player will collect items to the left and right of it that it shouldn't be able to. Often items will disappear before they've come close enough to touch the player sprite. How could I fix this?

**Comment by quinton-ashley** [comment]
@zOadT I'm still stuck on this. Do you have any ideas of what I can do?

**Comment by zOadT** [comment]
Hey!
I don't know how much you want to generalize your solution, but for this situation my initial idea to set this up would be a bit different:
Use sensor fixtures for the items and listen to the `beginContact` event (then you should be able to use the `isTouching` method on the contact). When you want the items to collide with each other you can define a non-sensor fixture on top of the sensor fixture (same position and shape) and prevent collisions with the player by setting appropriate collision masks (just be sure to set the density of the sensors to 0 in that case)

Otherwise, I think you have to check whether the fixtures collide manually (for polygons see [this example](https://piqnt.com/planck.js/PolyCollision), for more general cases you could maybe use the [distance function](https://piqnt.com/planck.js/DistanceTest)) But you probably already tried this and did not like it 😅

**Comment by quinton-ashley** [comment]
@zOadT thanks for the advice! I used sensors.

https://molleindustria.github.io/p5.play/v3_examples/index.html?fileName=pickup.js
