### ISSUE TITLE
Memory leak in planck?

### ISSUE THREAD

**Issue by quinton-ashley** [shakiba/planck.js#226]
User @ GalacticSeal on the p5.play discord made a bullet hell game and thinks there's a memory leak in planck:

```
Is data from removed sprites of groups left over that would cause extra use of RAM or a memory leak? I'm asking because I think there might be a memory leak from p5.play, as I know the final attack from my latest project causes everything to start lagging even after that spell is done and the projectiles are removed

Someone just had the webpage of the bullet hell crash because of a fatal memory error on the final spell card lol
There is definitely either a direct problem with the amount of memory that spell takes or a memory leak somewhere in the code that I don't know about
For right now, I guess people are just going to need higher-end PCs or something
```

<https://editor.p5js.org/GDD140-J_Chaput/full/XP4LGd8ZK>

Behind the scenes in p5.play I am using this function to remove planck bodies:

```js
 this.p.world.destroyBody(this.body);
 ```
 
 I am I missing something? How can I remove that body entirely to free up memory?

**Comment by photonstorm** [comment]
You can rule out if this is a memory leak or a browser gc issue using Dev Tools.

Run your intensive effect a few times, watch the memory increase, and then hit the 'collect garbage' icon in Dev Tools (trash can icon on the Memory tab). If memory drops, then the issue is _not_ with planck, because it obviously freed up its internal references and objects correctly. Otherwise, clicking this icon wouldn't make any difference if it was incorrectly holding on to them.

If memory doesn't drop significantly, then yes, there's an issue.

**Comment by quinton-ashley** [comment]
Thanks! I think I figured it out, now I set `this.body = null` after removing it and I think that works!
