### ISSUE TITLE
How to change a collider's center?

### ISSUE THREAD

**Issue by quinton-ashley** [shakiba/planck.js#233]
I tried using `body.sweep.setLocalCenter()` on a rectangular collider but while it does change how the sprite rotates the center of the collider seems to still be in the center when I use `getPosition`. How could I change the collider's origin?

**Comment by quinton-ashley** [comment]
@zOadT Could I get a bit of help with this? 🙏

**Comment by zOadT** [comment]
Hey! I don't know if I understand your question correctly, but I try to give some general advice:

In box2d center of mass and the origin of a body are two distinct points (see [this section](https://box2d.org/documentation/md__d_1__git_hub_box2d_docs_dynamics.html#autotoc_md58)). `getPosition` returns the body's origin. To get the center of mass I think you have to use `getWorldCenter`.

If (for whatever reason) you want the body origin to be the same as the center of mass: You can (instead of setting `setLocalCenter=P`) shift the fixtures of the body by `-P` and set `setLocalCenter=0` (setting `setLocalCenter`to zero means "center of mass == origin of body" by definition)

I hope this helps!

**Comment by quinton-ashley** [comment]
@zOadT genius! I will try that.

**Comment by quinton-ashley** [comment]
@zOadT It worked! Thank you so much. :)

```js
offsetCenter(x, y) {
	if (!this.body) return;

	let off = scaleTo(x, y, this.tileSize);
	for (let fxt = this.body.m_fixtureList; fxt; fxt = fxt.m_next) {
		let vertices = fxt.m_shape.m_vertices;
		for (let v of vertices) {
			v.x += off.x;
			v.y += off.y;
		}
	}
}
```
