### ISSUE TITLE
[SUGGESTION] rename `lib` to `src`

### ISSUE THREAD

**Issue by finscn** [shakiba/planck.js#55]
In most projects ,  the dir name`lib` means  dependencies (the 3rd lib) ,  `src` means the source code of current project.

So , I hope you could rename `lib` to `src`

**Comment by shakiba** [comment]
Since we migrated to typescript we started using src folder.

That said, according to [commonjs wiki](https://wiki.commonjs.org/wiki/Packages/1.0) and legacy [npm doc](https://docs.npmjs.com/cli/v6/configuring-npm/package-json), lib directory was recommended for project code. In fact before npm was popular, the folder that was used for dependencies was "vendor" directory. Using "src" folder, instead of lib, became popular with the rise of coffeescript, so that developers could use it for their uncompiled code (see [newer npm doc](https://docs.npmjs.com/cli/v9/configuring-npm/package-json)).
